name: Python CI

on: push
jobs:
  linter-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install poetry
          pip install flake8
          make install
      - name: lint application
        run: make lint